name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 최신 버전 사용

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USERNAME }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
          JAR_NAME: myapp.jar
          APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i $KEY $USER@$HOST << 'EOF'
            pkill -f $JAR_NAME || true
            rm -f $JAR_NAME
          EOF

          scp -o StrictHostKeyChecking=no -i $KEY build/libs/*.jar $USER@$HOST:~/$JAR_NAME

          ssh -o StrictHostKeyChecking=no -i $KEY $USER@$HOST << 'EOF'
            echo "$APPLICATION_YML" > ~/application.yml
            nohup java -jar ~/$JAR_NAME --spring.config.location=~/application.yml > app.log 2>&1 &
          EOF
